### ISSUE TITLE
[Enhancement proposal] Configuration profiles

### ISSUE THREAD

**Issue by aitorarjona** [lithops-cloud/lithops#1068]
Currently, Lithops can be configured:
 - by a config YAML file in ~/.lithops/config
 - by ENV vars
 - by directly passing configuration path or dict to a FunctionExecutor constructor

The standard and most convenient is using a configuration file. The problem with having only one config file is that, for a multi-cloud configuration, all parameters reside in the same config file, potentially being a mess.

I propose to create **configuration profiles**. The "default profile" is the `~/.lithops/config` file, but users could create new config files with different names (e.g. `~/.lithops/aws_lambda_testing`), and select the appropraite profile in the FunctionExecutor constructor (`FunctionExecutor(config_profile="aws_lambda_testing")`).

WDYT @JosepSampe

**Comment by JosepSampe** [comment]
Yes, good idea @aitorarjona 
Do you have an example of what the configuration file with profiles should look like?

**Comment by aitorarjona** [comment]
The idea is to keep `~/.lithops/config` file as the `default` profile for backwards compatibility, which will look the same as always, for example:

```yaml
lithops: 
    backend: localhost
    storage: localhost

localhost:
    worker_processes: 1
```

for testing.

Another profile for, for example, IBM Cloud in file ``~/.lithops/ibm` would look like this:
```yaml
lithops: 
    backend: ibm_cf
    storage: ibm_cos

ibm_cf:
    endpoint : ...
    namespace : ...
    api_key : ...

ibm_cos:
    storage_bucket: ...
    region : ...
```

and to select this configuration profile:
```python
FunctionExecutor(config_profile="aws_lambda_testing")
```
