### ISSUE TITLE
[AWS EC2] Add possiblity to specify EBS parameters, user data and enhanced monitoring

### ISSUE THREAD

**Issue by piotrkica** [lithops-cloud/lithops#1413]
Hi, 

I see no way to specify: Size, Throughput, Type and IOPS for EBS volumes of EC2 workers. Without this feature I cannot use Lithops (500GB per worker). Also I use _user_data_ to initialize workers and it is missing too.

Adding this would make moving to Lithops easier. My current solution uses Terraform for Launch Templates+ASG and missing options make migration much more difficult.

**Comment by JosepSampe** [comment]
Hi @piotrkica, Thank you for your feedback! In PR #1418, I added support for specifying EBS volumes in the config file, which ensures that all EC2 Lithops workers will have the specified EBS volumes attached. This should address the need for configuring Size, Throughput, Type, and IOPS for the EBS volumes.

In the next few days, I will also be adding support for `user_data`.

**Comment by piotrkica** [comment]
Thank you @JosepSampe for your PR. I can confirm that it works correctly.

**Comment by JosepSampe** [comment]
@piotrkica Can you describe what `user_data` you need to provide to the workers?

Lithops already makes use of this `user_data`:
```
#cloud-config
users:
    - name: {0}
      ssh_authorized_keys:
        - {1}
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: sudo
      shell: /bin/bash
```

So i want to know if we will need to reconcile both `user_data`, or simply append one after another.
