### ISSUE TITLE
Multiple serverless entries in the same configuration file

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#412]
Currently configuration file has a single entry
```
serverless:
    #runtime_timeout: 600
    #runtime_memory: 256
    #remote_invoker: True
    backend: <my_backend>
    runtime: <ny_runtime>
```

I want to extend this to enable multiple "serverless" entries, each configured for specific backend  with its runtime and specific configuration to that backend.

This way we can easily switch between serverless backends in a single workflow.

@JosepSampe what do you think?
