### ISSUE TITLE
cpu config for code engine doesn't take effect

### ISSUE THREAD

**Issue by shiyan0109** [lithops-cloud/lithops#504]
on lithops release 2.2.14

lithops_config file
```
code_engine:
    kubectl_config: xxx
    docker_user: xxx
    cpu: 200m
```

code
```
import lithops

iterdata = ['Gil', 'Dana', 'John', 'Scott']

def add_value(name):
    return 'Hello ' + name

if __name__ == '__main__':
    lt = lithops.FunctionExecutor(mode="serverless",
            backend='code_engine',
            log_level='DEBUG')
    lt.map(add_value,  iterdata)
    print (lt.get_result())
```

Check the jobDefinition created by the code automatically
```
 resources:
          requests:
            cpu: "1"
            memory: 512Mi
```

I expect the resource.requests.cpu is set to 200m instead of 1 (default value)
