### ISSUE TITLE
JSON Schema for Lithops configuration for IDE autocompletion

### ISSUE THREAD

**Issue by ephod** [lithops-cloud/lithops#721]
Hello,
I've created a JSON Schema v4 which is compatible with the current Lithops YAML configuration file.

Hopefully this will help a lot of new users with the initial setup configuration of Lithops. 

https://gist.github.com/ephod/2ae295f730d635936cb9061d5894ffdc

```yaml
# ...
redis:
  host: redislab.com
  port: 6379
  username: default
  db: 0
  password: foo
  ssl: True
```

Default values have been included and also required properties.

There are certain keyword arguments which were not documented for Redis (StrictRedis is an alias for Redis). These suggestions make it compatible for managed Redis clusters with TLS certificates.

## IDEs and text editors

* Visual Studio Code: https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings
* PyCharm: https://www.jetbrains.com/help/pycharm/json.html#ws_json_schema_add_custom

## JSON Schema Store

* URL: https://www.schemastore.org/json/
* Repository: https://github.com/SchemaStore/schemastore
